demo-blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  root 'posts#index'
end

demo-blog/app/models/post.rb
class Post < ApplicationRecord
end

demo-blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all

  end

  

  def new
    @post = Post.new

  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      redirect_to @post , message: "Post was created successfully"
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(posts_params)
      redirect_to @post
    else
      render 'edit'  
    end  
  end

  def show 
    @post = Post.find(params[:id])
  end  

  def edit
    @post = Post.find(params[:id])
  end

  def destroy

  end

  private

  def posts_params
  	params.require(:post).permit(:title, :content)
  end	

end

demo-blog/app/helpers/posts_helper.rb
module PostsHelper
end

demo-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <section class="hero is-primary is-medium">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
      <nav class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to 'Demo Blog', root_path, class: "navbar-item" %>
            <span class="navbar-burger burger" data-target="navbarMenuHeroA">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
              <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
            </div>
          </div>
        </div>
      </nav>
    </div>

    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">
          <%= yield :page_title %>
        </h1>
      </div>
    </div>
  </section>
    <%= yield %>
  </body>
</html>

demo-blog/app/views/posts/_form.html.erb
<div class="section">
	<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Create new post', class: "button is-primary" %>
    <% end %>
</div>    	

demo-blog/app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>
<%= render 'form' %>

demo-blog/app/views/posts/index.html.erb
</div><h1 class="title">Blog Index</h1>
<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to post.title, post  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= post.content %>
		    </div>
		
		  </div>
		</div>
		<% end %>
	</div>

demo-blog/app/views/posts/new.html.erb
<h1 class="title">New Blog</h1>

<%= render 'form' %>

demo-blog/app/views/posts/show.html.erb
<h1 class="title"> Show Page</h1>
<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Actions</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_post_path(@post), class:"button" %>
		  	</p>
		  	<p class="level-item">
				<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

		<div class="content">
			<%= @post.content %>
		</div>
	</div>
</section>